server:
  port: 8090
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    #发件人
    username: 26591798263@qq.com
    #授权码
    password: AWWDMGCTMCLBRSVB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ship?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    #控制台显示SQL
    show-sql: true
  security:
  user:
    password: 1234
    name: user